# Generated by Django 2.0.1 on 2018-02-27 09:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import restapi.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminActiveTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startDate', models.DateTimeField()),
                ('endDate', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LandingPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, null=True, upload_to=restapi.models.landingPageLocation)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('isReady', models.BooleanField(default=False)),
                ('lat', models.DecimalField(decimal_places=19, max_digits=23, null=True)),
                ('lng', models.DecimalField(decimal_places=19, max_digits=23, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('visibility', models.BooleanField(default=True)),
                ('description', models.CharField(max_length=1000, null=True)),
                ('zoom', models.IntegerField(null=True)),
                ('adminuser', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('lat', models.DecimalField(decimal_places=19, max_digits=23, null=True)),
                ('lng', models.DecimalField(decimal_places=19, max_digits=23, null=True)),
                ('name', models.CharField(max_length=255, null=True)),
                ('visibility', models.BooleanField(default=True)),
                ('radius', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('audioFile', models.FileField(blank=True, null=True, upload_to=restapi.models.audioFileLocation)),
                ('content_type', models.CharField(blank=True, max_length=255, null=True)),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='restapi.Location')),
            ],
        ),
        migrations.CreateModel(
            name='PointType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Polygon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.CharField(max_length=1000, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('strokeColor', models.CharField(blank=True, max_length=255, null=True)),
                ('strokeWeight', models.IntegerField(blank=True, null=True)),
                ('strokeOpacity', models.IntegerField(blank=True, null=True)),
                ('fillColor', models.CharField(blank=True, max_length=255, null=True)),
                ('fillOpacity', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tourist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paymentToken', models.CharField(max_length=1000, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startDate', models.DateTimeField(auto_now=True, null=True)),
                ('endDate', models.DateTimeField(default=restapi.models.paymentEndDate, null=True)),
                ('isProcessed', models.BooleanField(default=False)),
                ('paymentId', models.CharField(max_length=1000, null=True)),
                ('paymentType', models.CharField(max_length=255, null=True)),
                ('paymentAmount', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='restapi.Location')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='point',
            name='pointtypes',
            field=models.ManyToManyField(blank=True, to='restapi.PointType'),
        ),
        migrations.AddField(
            model_name='location',
            name='polygon',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='restapi.Polygon'),
        ),
        migrations.AddField(
            model_name='adminactivetime',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='restapi.Location'),
        ),
        migrations.AddField(
            model_name='adminactivetime',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
