# Generated by Django 2.0.1 on 2018-03-14 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='img',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
