# Generated by Django 2.0.1 on 2018-03-25 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0003_point_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='img',
            field=models.CharField(default='/not_set', max_length=255),
        ),
    ]
