# Generated by Django 2.0.1 on 2018-03-27 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0004_auto_20180325_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='description',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
